name: Build TensorFlow Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - shell: cmd
        run: |
          msbuild ./build/TensorFlow.sln /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}}
